---
tautulli_enabled: true
tautulli_available_externally: "true"

# directories
tautulli_config_directory: "{{ docker_home }}/tautulli/config"

# uid / gid
tautulli_user_id: "0"
tautulli_group_id: "0"

# network
tautulli_hostname: "tautulli"
tautulli_port: "8185"

# specs
tautulli_memory: "1g"
