---
- hosts: all

  pre_tasks:
    - import_tasks: tasks/users.yml
      tags: users

  roles:
    ###
    ### Requirements
    ###
    - role: bertvv.samba
      tags:
        - samba
        - skip_ansible_lint

    - role: geerlingguy.nfs
      tags:
        - nfs
        - skip_ansible_lint

    - role: geerlingguy.docker
      tags:
        - docker
        - skip_ansible_lint

    ###
    ### Ansible-NAS Roles
    ###
    - role: ansible-nas-general
      tags:
        - ansible-nas-general
        - ansible-nas

    - role: ansible-nas-docker
      tags:
        - ansible-nas-docker
        - ansible-nas

    ###
    ### Applications
    ###
    - role: airsonic
      tags:
        - airsonic
      when: (airsonic_enabled | default(True))

    - role: bazarr
      tags:
        - bazarr
      when: (bazarr_enabled | default(True))

    - role: bitwarden
      tags:
        - bitwarden
      when: (bitwarden_enabled | default(True))

    - role: booksonic
      tags:
        - booksonic
      when: (booksonic_enabled | default(True))

    - role: cloudcmd
      tags:
        - cloudcmd
      when: (cloudcmd_enabled | default(True))

    - role: cloudflare_ddns
      tags:
        - cloudflare_ddns
      when: (cloudflare_ddns_enabled | default(True))

    - role: couchpotato
      tags:
        - couchpotato
      when: (couchpotato_enabled | default(True))

    - role: dashy
      tags:
        - dashy
      when: (dashy_enabled | default(True))

    - role: deluge
      tags:
        - deluge
      when: (deluge_enabled | default(True))

    - role: dokuwiki
      tags:
        - dokuwiki
      when: (dokuwiki_enabled | default(True))

    - role: duplicacy
      tags:
        - duplicacy
      when: (duplicacy_enabled | default(True))

    - role: duplicati
      tags:
        - duplicati
      when: (duplicati_enabled | default(True))

    - role: emby
      tags:
        - emby
      when: (emby_enabled | default(True))

    - role: esphome
      tags:
        - esphome
      when: (esphome_enabled | default(True))

    - role: firefly
      tags:
        - firefly
      when: (firefly_enabled | default(True))

    - role: freshrss
      tags:
        - freshrss
      when: (freshrss_enabled | default(True))

    - role: get_iplayer
      tags:
        - get_iplayer
      when: (get_iplayer_enabled | default(True))

    - role: gitea
      tags:
        - gitea
      when: (gitea_enabled | default(True))

    - role: gitlab
      tags:
        - gitlab
      when: (gitlab_enabled | default(False))

    - role: glances
      tags:
        - glances
      when: (glances_enabled | default(True))

    - role: gotify
      tags:
        - gotify
      when: (gotify_enabled | default(True))

    - role: healthchecks.io
      tags:
        - healthchecks.io
      when: (healthchecks_enabled | default(False))

    - role: heimdall
      tags:
        - heimdall
      when: (heimdall_enabled | default(True))

    - role: homeassistant
      tags:
        - homeassistant
      when: (homeassistant_enabled | default(True))

    - role: jellyfin
      tags:
        - jellyfin
      when: (jellyfin_enabled | default(True))

    - role: lidarr
      tags:
        - lidarr
      when: (lidarr_enabled | default(True))

    - role: mealie
      tags:
        - mealie
      when: (mealie_enabled | default(True))

    - role: minecraft-server
      tags:
        - minecraft-server
      when: (minecraft_server_enabled | default(True))

    - role: minidlna
      tags:
        - minidlna
      when: (minidlna_enabled | default(True))

    - role: miniflux
      tags:
        - miniflux
      when: (miniflux_enabled | default(True))

    - role: mosquitto
      tags:
        - mosquitto
      when: (mosquitto_enabled | default(True))

    - role: mylar
      tags:
        - mylar
      when: (mylar_enabled | default(True))

    - role: mymediaforalexa
      tags:
        - mymediaforalexa
      when: (mymediaforalexa_enabled | default(True))

    - role: n8n
      tags:
        - n8n_enabled
      when: (n8n_enabled | default(True))

    - role: navidrome
      tags:
        - navidrome
      when: (navidrome_enabled | default(True))

    - role: netbootxyz
      tags:
        - netbootxyz
      when: (netbootxyz_enabled | default(True))

    - role: netdata
      tags:
        - netdata
      when: (netdata_enabled | default(True))

    - role: nextcloud
      tags:
        - nextcloud
      when: (nextcloud_enabled | default(True))

    - role: nzbget
      tags:
        - nzbget
      when: (nzbget_enabled | default(True))

    - role: octoprint
      tags:
        - octoprint
      when: (octoprint_enabled | default(True))

    - role: organizr
      tags:
        - organizr
      when: (organizr_enabled | default(True))

    - role: overseerr
      tags:
        - overseerr
      when: (overseerr_enabled | default(True))

    - role: paperless_ng
      tags:
        - paperless_ng
      when: (paperless_ng_enabled | default(True))

    - role: piwigo
      tags:
        - piwigo
      when: (piwigo_enabled | default(True))

    - role: portainer
      tags:
        - portainer
      when: (portainer_enabled | default(True))

    - role: prowlarr
      tags:
        - prowlarr
      when: (prowlarr_enabled | default(True))

    - role: pyload
      tags:
        - pyload
      when: (pyload_enabled | default(True))

    - role: ombi
      tags:
        - ombi
      when: (ombi_enabled | default(True))

    - role: plex
      tags:
        - plex
      when: (plex_enabled | default(True))

    - role: pytivo
      tags:
        - pytivo
      when: (pytivo_enabled | default(True))

    - role: radarr
      tags:
        - radarr
      when: (radarr_enabled | default(True))

    - role: sabnzbd
      tags:
        - sabnzbd
      when: (sabnzbd_enabled | default(True))

    - role: route53_ddns
      tags:
        - route53_ddns
      when: (route53_ddns_enabled | default(True))

    - role: rssbridge
      tags:
        - rssbridge
      when: (rssbridge_enabled | default(True))

    - role: sickchill
      tags:
        - sickchill
      when: (sickchill_enabled | default(True))

    - role: sonarr
      tags:
        - sonarr
      when: (sonarr_enabled | default(True))

    - role: speedtest-tracker
      tags:
        - speedtest-tracker
      when: (speedtest_tracker_enabled | default(True))

    - role: syncthing
      tags:
        - syncthing
      when: (syncthing_enabled | default(True))

    - role: tautulli
      tags:
        - tautulli
      when: (tautulli_enabled | default(True))

    - role: tiddlywiki
      tags:
        - tiddlywiki
      when: (tiddlywiki_enabled | default(True))

    - role: transmission
      tags:
        - transmission
      when: (transmission_enabled | default(True))

    - role: transmission-with-openvpn
      tags:
        - transmission_with_openvpn
      when: (transmission_with_openvpn_enabled | default(True))

    - role: utorrent
      tags:
        - utorrent
      when: (utorrent_enabled | default(True))

    - role: traefik
      tags:
        - traefik
      when: (traefik_enabled | default(True))

    - role: youtubedlmaterial
      tags:
        - youtubedlmaterial
      when: (youtubedlmaterial_enabled | default(True))

    - role: watchtower
      tags:
        - watchtower
      when: (watchtower_enabled | default(True))

    - role: znc
      tags:
        - znc
      when: (znc_enabled | default(True))

  tasks:
    - import_tasks: tasks/thelounge.yml
      when: (thelounge_enabled | default(True))
      tags: thelounge

    - import_tasks: tasks/timemachine.yml
      when: (timemachine_enabled | default(True))
      tags: timemachine

    - import_tasks: tasks/guacamole.yml
      when: (guacamole_enabled | default(True))
      tags: guacamole

    - import_tasks: tasks/joomla.yml
      when: (joomla_enabled | default(True))
      tags: joomla

    - import_tasks: tasks/wallabag.yml
      when: (wallabag_enabled | default(True))
      tags: wallabag

    - import_tasks: tasks/calibre.yml
      when: (calibre_enabled | default(True))
      tags: calibre

    - import_tasks: tasks/openhab.yml
      when: (openhab_enabled | default(True))
      tags: openhab

    - import_tasks: tasks/krusader.yml
      when: (krusader_enabled | default(True))
      tags: krusader

    - import_tasks: tasks/ubooquity.yml
      when: (ubooquity_enabled | default(True))
      tags: ubooquity

    - import_tasks: tasks/virtual_desktop.yml
      when: (virtual_desktop_enabled | default(True))
      tags: virtual_desktop
