---

tiddlywiki_enabled: true
tiddlywiki_available_externally: "true"

# Data directory for config file
tiddlywiki_data_directory: "{{ docker_home }}/tiddlywiki"

# Basic auth
# tiddlywiki_username:
# tiddlywiki_password:

# Node low memory
# tiddlywiki_node_memory:

# Server debugging
# tiddlywiki_debug_level: none # full

# Networking
tiddlywiki_port: 8092
tiddlywiki_hostname: tiddlywiki

# Container
tiddlywiki_memory: 512MB
